/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import classes.Cola;

public class ColaUi extends javax.swing.JPanel {

    /**
     * Creates new form ColaUi
     */
    public ColaUi() {
        initComponents();
    }
    
    public void updateUiQueue(Cola cola){
        this.colaLabel.setText(cola.print());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        colaLabel = new javax.swing.JLabel();
        headLabel = new javax.swing.JLabel();
        tailLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPane.setBackground(new java.awt.Color(0, 0, 0));
        mainPane.setForeground(new java.awt.Color(255, 255, 255));
        mainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Cola de prioridad");
        mainPane.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        colaLabel.setBackground(new java.awt.Color(255, 255, 255));
        ScrollPane.setViewportView(colaLabel);

        mainPane.add(ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 310, 50));

        headLabel.setForeground(new java.awt.Color(255, 255, 255));
        headLabel.setText("Head");
        mainPane.add(headLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        tailLabel.setForeground(new java.awt.Color(255, 255, 255));
        tailLabel.setText("Tail");
        mainPane.add(tailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel colaLabel;
    private javax.swing.JLabel headLabel;
    private javax.swing.JPanel mainPane;
    private javax.swing.JLabel tailLabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    public void setTitulo(String text){
        this.titulo.setText(text);
    }
}
